// Builds the quarter debrief's small archipelago chart from the province map.
import { readFileSync, writeFileSync } from "node:fs";
import { topology } from "topojson-server";
import { merge } from "topojson-client";
import { presimplify, simplify } from "topojson-simplify";
import { geoArea, geoMercator, geoPath } from "d3-geo";

const W = 490,
  H = 180;
const geo = JSON.parse(readFileSync("public/data/provinces.geojson", "utf8"));
const src = readFileSync("src/engine/gameRegions.ts", "utf8");
const regions = [
  ...src.matchAll(/id: "(\w+)",[\s\S]*?provinceIds: \[([^\]]*)\]/g),
].map((m) => ({
  id: m[1],
  provinces: [...m[2].matchAll(/"(\d+)"/g)].map((x) => x[1]),
}));
// d3 treats counter-clockwise (RFC 7946) rings as the rest of the globe.
const rewind = (poly) =>
  geoArea({ type: "Polygon", coordinates: poly }) > 2 * Math.PI
    ? poly.map((ring) => [...ring].reverse())
    : poly;
for (const f of geo.features)
  if (f.geometry.type === "Polygon")
    f.geometry.coordinates = rewind(f.geometry.coordinates);
  else f.geometry.coordinates = f.geometry.coordinates.map(rewind);
let topo = topology({ p: geo });
topo = simplify(presimplify(topo), 0.004);
const projection = geoMercator().fitExtent(
  [
    [10, 10],
    [W - 10, H - 10],
  ],
  geo,
);
const path = geoPath(projection);
const round = (d) =>
  d.replace(/(\d+)\.\d+/g, (n) => String(Math.round(Number(n))));
const out = {};
for (const region of regions) {
  const shape = merge(
    topo,
    topo.objects.p.geometries.filter((g) =>
      region.provinces.includes(String(g.id)),
    ),
  );
  // Keep recognizable islands; drop specks smaller than a few chart pixels.
  shape.coordinates = shape.coordinates.map(rewind);
  const area = (poly) => path.area({ type: "Polygon", coordinates: poly });
  shape.coordinates = shape.coordinates.filter((poly) => area(poly) > 3);
  const biggest = [...shape.coordinates].sort((a, b) => area(b) - area(a))[0];
  const [x, y] = path.centroid({ type: "Polygon", coordinates: biggest });
  out[region.id] = {
    d: round(path(shape)),
    anchor: [Math.round(x), Math.round(y)],
  };
}
writeFileSync(
  "src/debriefMap.ts",
  `// Generated by scripts/debrief-map.mjs from public/data/provinces.geojson.\nimport type { RegionId } from "./engine/economy/types";\n\nexport const DEBRIEF_MAP_SIZE = [${W}, ${H}] as const;\nexport const DEBRIEF_ISLANDS: Record<RegionId, { d: string; anchor: [number, number] }> = ${JSON.stringify(out, null, 2)};\n`,
);
console.log(
  Object.fromEntries(
    Object.entries(out).map(([k, v]) => [k, [v.d.length, v.anchor]]),
  ),
);
